apiVersion: v1
kind: Template
labels:
  template: hdd-supervisor
metadata:
  name: hdd-supervisor
  annotations:
    description: hdd-supervisor
objects:
- apiVersion: v1
  kind: Pod
  metadata:
    generateName: hdd-supervisor
    labels:
      app: hdd-supervisor
      deploymentconfig: hdd-supervisor
    name: hdd-supervisor
    namespace: hdd-supervisor
  spec:
    containers:
      - image: >-
          registry.devshift.net/fabric8-hdd/openshift-hdd-supervisor:latest
        imagePullPolicy: Always
        name: hdd-supervisor
        env:
        - name: HDD_SUPERVISOR_PORT
          value: ${SUPERVISOR_PORT}
        ports:
        - containerPort: ${{SUPERVISOR_PORT}}
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /api/v1.0/readiness
            port: ${{SUPERVISOR_PORT}}
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 60
          timeoutSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/v1.0/liveness
            port: ${{SUPERVISOR_PORT}}
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 60
          timeoutSeconds: 10
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1024Mi"
            cpu: "1000m"
        securityContext:
          privileged: false
    dnsPolicy: ClusterFirst
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: hdd-supervisor
    name: hdd-supervisor
    namespace: hdd-supervisor
  spec:
    ports:
      - name: supervisor-tcp
        port: ${{SUPERVISOR_PORT}}
        protocol: TCP
        targetPort: ${{SUPERVISOR_PORT}}
    selector:
      deploymentconfig: hdd-supervisor
- apiVersion: v1
  kind: Route
  metadata:
    name: hdd-supervisor
    namespace: hdd-supervisor
  spec:
    host: ${SUPERVISOR_HOSTNAME}
    port:
      targetPort: supervisor-tcp
    to:
      kind: Service
      name: hdd-supervisor
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: hdd-supervisor
    name: hdd-supervisor
    namespace: hdd-supervisor
  spec:
    replicas: 1
    selector:
      app: hdd-supervisor
      deploymentconfig: hdd-supervisor
    template:
      metadata:
        labels:
          app: hdd-supervisor
          deploymentconfig: hdd-supervisor
      spec:
        containers:
          - image: >-
              registry.devshift.net/fabric8-hdd/openshift-hdd-supervisor:latest
            imagePullPolicy: Always
            name: hdd-supervisor
            ports:
              - containerPort: ${{SUPERVISOR_PORT}}
                protocol: TCP
            resources: {}
        dnsPolicy: ClusterFirst
    triggers:
      - type: ConfigChange
      - imageChangeParams:
          automatic: true
          containerNames:
            - hdd-supervisor
          from:
            kind: ImageStreamTag
            name: 'hdd-supervisor:latest'
            namespace: hdd-supervisor
        type: ImageChange

parameters:
- name: SUPERVISOR_PORT
  description: Port number that supervisor service will be exposed on.
  required: true
  value: "9090"
- name: SUPERVISOR_HOSTNAME
  description: Parameterised hostname route for the supervisor service.
  required: false